const jobTitles = {
    leadershipTitles: [
      'Team Leader',
      'Manager',
      'Assistant Manager',
      'Executive',
      'Director',
      'Coordinator',
      'Administrator',
      'Controller',
      'Officer',
      'Organizer',
      'Supervisor',
      'Superintendent',
      'Head',
      'Overseer',
      'Chief',
      'Foreman',
      'Controller',
      'Principal',
      'President',
      'Lead',
    ],
    itTitles: [
      'Computer Scientist',
      'IT Professional',
      'UX Designer & UI Developer',
      'SQL Developer',
      'Web Designer',
      'Web Developer',
      'Help Desk Worker/Desktop Support',
      'Software Engineer',
      'Data Entry',
      'DevOps Engineer',
      'Computer Programmer',
      'Network Administrator',
      'Information Security Analyst',
      'Artificial Intelligence Engineer',
      'Cloud Architect',
      'IT Manager',
      'Technical Specialist',
      'Application Developer',
      'Chief Technology Officer (CTO)',
      'Chief Information Officer (CIO)',
    ],
    salesTitles: [
      'Sales Associate',
      'Sales Representative',
      'Sales Manager',
      'Retail Worker',
      'Store Manager',
      'Sales Representative',
      'Sales Manager',
      'Real Estate Broker',
      'Sales Associate',
      'Cashier',
      'Store Manager',
      'Account Executive',
      'Account Manager',
      'Area Sales Manager',
      'Direct Salesperson',
      'Director of Inside Sales',
      'Outside Sales Manager',
      'Sales Analyst',
      'Market Development Manager',
      'B2B Sales Specialist',
      'Sales Engineer',
      'Merchandising Associate',
    ],
    costructionTitles: [
      'Construction Worker',
      'Taper',
      'Plumber',
      'Heavy Equipment Operator',
      'Vehicle or Equipment Cleaner',
      'Carpenter',
      'Electrician',
      'Painter',
      'Welder',
      'Handyman',
      'Boilermaker',
      'Crane Operator',
      'Building Inspector',
      'Pipefitter',
      'Sheet Metal Worker',
      'Iron Worker',
      'Mason',
      'Roofer',
      'Solar Photovoltaic Installer',
      'Well Driller',
    ],
    ownerTitles: [
      'CEO',
      'Proprietor',
      'Principal',
      'Owner',
      'President',
      'Founder',
      'Administrator',
      'Director',
      'Managing Partner',
      'Managing Member',
    ],
    positionTitles: [
      'Board of Directors',
      'C-Level or C-Suite',
      'Shareholders',
      'Managers',
      'Supervisors',
      'Front-Line Employees',
      'Quality Control',
      'Human Resources',
      'Accounting Staff',
      'Marketing Staff',
      'Purchasing Staff',
      'Shipping and Receiving Staff',
      'Office Manager',
      'Receptionist',
    ],
    hospitality: [
      'Housekeeper',
      'Flight Attendant',
      'Travel Agent',
      'Hotel Front Door Greeter',
      'Bellhop',
      'Cruise Director',
      'Entertainment Specialist',
      'Hotel Manager',
      'Front Desk Associate',
      'Front Desk Manager',
      'Concierge',
      'Group Sales',
      'Event Planner',
      'Porter',
      'Spa Manager',
      'Wedding Coordinator',
      'Cruise Ship Attendant',
      'Casino Host',
      'Hotel Receptionist',
      'Reservationist',
      'Events Manager',
      'Meeting Planner',
      'Lodging Manager',
      'Director of Maintenance',
      'Valet',
    ],
  };
  
  module.exports = jobTitles;
  